### ISSUE TITLE
'vllm.engine.metrics' has no attribute 'StatLogger'.

### ISSUE THREAD

**Issue by Debangsha1992** [Emerging-AI/ENOVA#29]
When I run `enova enode run --model mistralai/Mistral-7B-Instruct-v0.1 --host 127.0.0.1 --port 9199` I get the following error:
`AttributeError: module 'vllm.engine.metrics' has no attribute 'StatLogger'. Did you mean: 'StatLoggerBase'?`

**Comment by Debangsha1992** [comment]
The reason is explained below:
The vllm has the attribute `StatLoggerBase` and not `StatLogger`.

ENOVA/llmo/enova-instrumentation-llmo/enova/llmo/instrumentation/vllm/__init__.py:

  ```
  8  from wrapt import wrap_function_wrapper
    9  
   10: from .wrappers import forward_wrapper, llmengine_init_wrapper, statlogger_init_wrapper
   11  
   12  _instruments = ("vllm >= v0.3.1",)
   ..
   75              self._apply_trace_wrapper(tracer, wrapper_method)
   76  
   77:         statlogger_package = "vllm.engine.metrics"
   78:         statlogger_object = "StatLogger"
   79:         statlogger_method = "__init__"
   80:         if module_exists(statlogger_package):
   81              wrap_function_wrapper(
   82:                 statlogger_package,
   83:                 f"{statlogger_object}.{statlogger_method}",
   84:                 statlogger_init_wrapper(self.service_name)
   85              )
   86              self.instrumented_methods.append({
   87:                 "package": statlogger_package,
   88:                 "object": statlogger_object,
   89:                 "method": statlogger_method
   90              })
   91  
```

**Comment by Tao-EmergingAI** [comment]
What is the version of vllm? 

ENOVA will also collect the metrics that vllm generates. vllm optimizes their metric APIs after v0.3.1. 
We have adapted the different versions of vllm. You may update the version of vllm, or install the corresponding version of ENOVA.
